require:
  - rubocop-graphql
  - rubocop-rspec
  - rubocop-rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

AllCops:
  NewCops: enable

# rubocop-rails

RSpec/MultipleMemoizedHelpers:
  Enabled: false
