require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

Naming/VariableNumber:
  EnforcedStyle: snake_case

AllCops:
  NewCops: enable

# rubocop-rails

RSpec/MultipleExpectations:
  Max: 2
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: should
