plugins:
  # - rubocop-capybara
  # - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-rspec_rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 180

# rubocop-rails

RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: should
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Custom Exclusions

Naming/PredicatePrefix:
  Exclude: &graphql_type_exclusions
    - "app/graphql/types/**/*"

Naming/PredicateMethod:
  Exclude: *graphql_type_exclusions

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "config/environments/*.rb"
    - "spec/**/*"
