plugins:
  # - rubocop-capybara
  # - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-rspec_rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 180

# rubocop-rails

RSpec/MultipleExpectations:
  Max: 2
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: should

# Custom Exclusions

Naming/PredicateName:
  Exclude:
    - "app/graphql/types/**/*"
Naming/PredicateMethod:
  Exclude:
    - "app/graphql/types/**/*"
