version: "3.7"

services:
  redis:
    container_name: photonia_redis
    image: redis:6.2
    ports:
      - '6379:6379'
    # sysctls:
      # net.core.somaxconn: '511'
      # vm.overcommit_memory: '1'
    volumes:
      - redis:/var/lib/redis/data

  photonia:
    container_name: photonia_app
    build: .
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      HISTFILE: /root/history/.bash_history
    stdin_open: true
    tty: true
    volumes:
      - .:/photonia
      - bash_history:/root/history/

  sidekiq:
    container_name: photonia_sidekiq
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/photonia

volumes:
  bash_history:
  redis:
