# frozen_string_literal: true

class FlickrClaimsController < ApplicationController
  # CSRF protection is skipped for these actions as they are accessed via email links.
  # Security is ensured through signed tokens generated by ActiveSupport::MessageVerifier
  # which expire after 30 days and are tied to specific claim IDs.
  # lgtm[rb/csrf-protection-disabled]
  skip_before_action :verify_authenticity_token, only: [:approve, :deny]

  def approve
    claim_id = params[:claim_id]
    token = params[:token]

    result = FlickrUserClaimService.approve_claim_by_token(claim_id, token)

    respond_to do |format|
      format.html do
        if result[:success]
          render :approve
        else
          @error = result[:error]
          render :error, status: :unprocessable_entity
        end
      end
      format.json do
        if result[:success]
          render json: { success: true }, status: :ok
        else
          render json: { success: false, error: result[:error] }, status: :unprocessable_entity
        end
      end
    end
  end

  def deny
    claim_id = params[:claim_id]
    token = params[:token]

    result = FlickrUserClaimService.deny_claim_by_token(claim_id, token)

    respond_to do |format|
      format.html do
        if result[:success]
          render :deny
        else
          @error = result[:error]
          render :error, status: :unprocessable_entity
        end
      end
      format.json do
        if result[:success]
          render json: { success: true }, status: :ok
        else
          render json: { success: false, error: result[:error] }, status: :unprocessable_entity
        end
      end
    end
  end
end
