name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PHOTONIA_DATABASE_URL: postgres://postgres:postgres@localhost/

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ github.event.repository.name }}.${{ github.sha }}
      - name: Run rspec tests
        run: |
          docker run -e PHOTONIA_DATABASE_URL=$PHOTONIA_DATABASE_URL ${{ github.event.repository.name }}.${{ github.sha }} bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
