name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ github.event.repository.name }}.${{ github.sha }}
      - name: Run rspec tests
        run: |
          docker run ${{ github.event.repository.name }}.${{ github.sha }} bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
